// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAlbumToPlaylist(arg1) {
  return window['go']['server']['App']['AddAlbumToPlaylist'](arg1);
}

export function AddSongsToPlaylist(arg1) {
  return window['go']['server']['App']['AddSongsToPlaylist'](arg1);
}

export function AddYouTubeLink(arg1) {
  return window['go']['server']['App']['AddYouTubeLink'](arg1);
}

export function AnalyseLibraryAudioEmbeddings() {
  return window['go']['server']['App']['AnalyseLibraryAudioEmbeddings']();
}

export function AudioDebugOutputRMS() {
  return window['go']['server']['App']['AudioDebugOutputRMS']();
}

export function AudioGetCurrentDevice() {
  return window['go']['server']['App']['AudioGetCurrentDevice']();
}

export function AudioGetDuration() {
  return window['go']['server']['App']['AudioGetDuration']();
}

export function AudioGetFrequencyData() {
  return window['go']['server']['App']['AudioGetFrequencyData']();
}

export function AudioGetPosition() {
  return window['go']['server']['App']['AudioGetPosition']();
}

export function AudioGetStatus() {
  return window['go']['server']['App']['AudioGetStatus']();
}

export function AudioIsLocalMuted() {
  return window['go']['server']['App']['AudioIsLocalMuted']();
}

export function AudioIsPaused() {
  return window['go']['server']['App']['AudioIsPaused']();
}

export function AudioIsPlaying() {
  return window['go']['server']['App']['AudioIsPlaying']();
}

export function AudioListDevices() {
  return window['go']['server']['App']['AudioListDevices']();
}

export function AudioLiveLoudnessCorrectionGain() {
  return window['go']['server']['App']['AudioLiveLoudnessCorrectionGain']();
}

export function AudioPause() {
  return window['go']['server']['App']['AudioPause']();
}

export function AudioPlay(arg1, arg2) {
  return window['go']['server']['App']['AudioPlay'](arg1, arg2);
}

export function AudioResume() {
  return window['go']['server']['App']['AudioResume']();
}

export function AudioSeek(arg1) {
  return window['go']['server']['App']['AudioSeek'](arg1);
}

export function AudioSetDevice(arg1) {
  return window['go']['server']['App']['AudioSetDevice'](arg1);
}

export function AudioSetEqualizer(arg1) {
  return window['go']['server']['App']['AudioSetEqualizer'](arg1);
}

export function AudioSetNormalisationGain(arg1) {
  return window['go']['server']['App']['AudioSetNormalisationGain'](arg1);
}

export function AudioSetNowPlayingMetadata(arg1) {
  return window['go']['server']['App']['AudioSetNowPlayingMetadata'](arg1);
}

export function AudioSetVolume(arg1) {
  return window['go']['server']['App']['AudioSetVolume'](arg1);
}

export function AudioStartLiveLoudnessCorrection(arg1) {
  return window['go']['server']['App']['AudioStartLiveLoudnessCorrection'](arg1);
}

export function AudioStartWebViewTap() {
  return window['go']['server']['App']['AudioStartWebViewTap']();
}

export function AudioStop() {
  return window['go']['server']['App']['AudioStop']();
}

export function AudioStopLiveLoudnessCorrection() {
  return window['go']['server']['App']['AudioStopLiveLoudnessCorrection']();
}

export function AudioStopWebViewTap() {
  return window['go']['server']['App']['AudioStopWebViewTap']();
}

export function AutoSyncLyrics(arg1) {
  return window['go']['server']['App']['AutoSyncLyrics'](arg1);
}

export function AutoSyncPairedDevices() {
  return window['go']['server']['App']['AutoSyncPairedDevices']();
}

export function CDApplyMetadata(arg1) {
  return window['go']['server']['App']['CDApplyMetadata'](arg1);
}

export function CDApplyVocaDBMetadata(arg1) {
  return window['go']['server']['App']['CDApplyVocaDBMetadata'](arg1);
}

export function CDScan() {
  return window['go']['server']['App']['CDScan']();
}

export function CDSearchTOC(arg1) {
  return window['go']['server']['App']['CDSearchTOC'](arg1);
}

export function CDSearchText(arg1) {
  return window['go']['server']['App']['CDSearchText'](arg1);
}

export function CDSearchVocaDB(arg1) {
  return window['go']['server']['App']['CDSearchVocaDB'](arg1);
}

export function CDStartRip(arg1) {
  return window['go']['server']['App']['CDStartRip'](arg1);
}

export function ClearLyricsSyncModelCache() {
  return window['go']['server']['App']['ClearLyricsSyncModelCache']();
}

export function ConfirmSyncPairing(arg1, arg2, arg3, arg4) {
  return window['go']['server']['App']['ConfirmSyncPairing'](arg1, arg2, arg3, arg4);
}

export function CreatePlaylist(arg1) {
  return window['go']['server']['App']['CreatePlaylist'](arg1);
}

export function DeletePlaylist(arg1) {
  return window['go']['server']['App']['DeletePlaylist'](arg1);
}

export function DeleteSongs(arg1, arg2) {
  return window['go']['server']['App']['DeleteSongs'](arg1, arg2);
}

export function DiscoverSyncDevices(arg1) {
  return window['go']['server']['App']['DiscoverSyncDevices'](arg1);
}

export function DownloadSyncTrack(arg1, arg2) {
  return window['go']['server']['App']['DownloadSyncTrack'](arg1, arg2);
}

export function EmbedDebugLog(arg1) {
  return window['go']['server']['App']['EmbedDebugLog'](arg1);
}

export function GenerateMoodSpecial(arg1, arg2) {
  return window['go']['server']['App']['GenerateMoodSpecial'](arg1, arg2);
}

export function GetAllLoudnessData() {
  return window['go']['server']['App']['GetAllLoudnessData']();
}

export function GetAllPlaylists() {
  return window['go']['server']['App']['GetAllPlaylists']();
}

export function GetArtworkAsDataURL(arg1) {
  return window['go']['server']['App']['GetArtworkAsDataURL'](arg1);
}

export function GetArtworksDir() {
  return window['go']['server']['App']['GetArtworksDir']();
}

export function GetAudioEmbedStatus() {
  return window['go']['server']['App']['GetAudioEmbedStatus']();
}

export function GetE2EEmbedVideoID() {
  return window['go']['server']['App']['GetE2EEmbedVideoID']();
}

export function GetLANAddress() {
  return window['go']['server']['App']['GetLANAddress']();
}

export function GetLibraryForNormalize() {
  return window['go']['server']['App']['GetLibraryForNormalize']();
}

export function GetLoudnessValue(arg1) {
  return window['go']['server']['App']['GetLoudnessValue'](arg1);
}

export function GetLyrics(arg1) {
  return window['go']['server']['App']['GetLyrics'](arg1);
}

export function GetLyricsSyncResourceStatus() {
  return window['go']['server']['App']['GetLyricsSyncResourceStatus']();
}

export function GetMTPDevices() {
  return window['go']['server']['App']['GetMTPDevices']();
}

export function GetPairingQRDataURL() {
  return window['go']['server']['App']['GetPairingQRDataURL']();
}

export function GetPairingURL() {
  return window['go']['server']['App']['GetPairingURL']();
}

export function GetPerformanceSnapshot() {
  return window['go']['server']['App']['GetPerformanceSnapshot']();
}

export function GetPlaylistDetails(arg1) {
  return window['go']['server']['App']['GetPlaylistDetails'](arg1);
}

export function GetSettings() {
  return window['go']['server']['App']['GetSettings']();
}

export function GetSidecarTargetDevice() {
  return window['go']['server']['App']['GetSidecarTargetDevice']();
}

export function GetSituationPlaylists() {
  return window['go']['server']['App']['GetSituationPlaylists']();
}

export function GetUnifiedLibrary() {
  return window['go']['server']['App']['GetUnifiedLibrary']();
}

export function GetYouTubeEmbedLoudness(arg1) {
  return window['go']['server']['App']['GetYouTubeEmbedLoudness'](arg1);
}

export function GetYouTubeEmbedURL(arg1) {
  return window['go']['server']['App']['GetYouTubeEmbedURL'](arg1);
}

export function GetYouTubeInfo(arg1) {
  return window['go']['server']['App']['GetYouTubeInfo'](arg1);
}

export function HandleLyricsDrop(arg1) {
  return window['go']['server']['App']['HandleLyricsDrop'](arg1);
}

export function IncrementPlayCount(arg1) {
  return window['go']['server']['App']['IncrementPlayCount'](arg1);
}

export function ListPairedRemoteDevices() {
  return window['go']['server']['App']['ListPairedRemoteDevices']();
}

export function ListSyncDevices() {
  return window['go']['server']['App']['ListSyncDevices']();
}

export function LoadLibrary() {
  return window['go']['server']['App']['LoadLibrary']();
}

export function LoadPlayCounts() {
  return window['go']['server']['App']['LoadPlayCounts']();
}

export function MTPDeleteFile(arg1) {
  return window['go']['server']['App']['MTPDeleteFile'](arg1);
}

export function MTPDispose() {
  return window['go']['server']['App']['MTPDispose']();
}

export function MTPDownloadFiles(arg1) {
  return window['go']['server']['App']['MTPDownloadFiles'](arg1);
}

export function MTPFetchDeviceInfo() {
  return window['go']['server']['App']['MTPFetchDeviceInfo']();
}

export function MTPFetchStorages() {
  return window['go']['server']['App']['MTPFetchStorages']();
}

export function MTPGetUntransferredSongs(arg1) {
  return window['go']['server']['App']['MTPGetUntransferredSongs'](arg1);
}

export function MTPInitialize() {
  return window['go']['server']['App']['MTPInitialize']();
}

export function MTPMakeDirectory(arg1) {
  return window['go']['server']['App']['MTPMakeDirectory'](arg1);
}

export function MTPSelectDownloadFolder() {
  return window['go']['server']['App']['MTPSelectDownloadFolder']();
}

export function MTPUploadFiles(arg1) {
  return window['go']['server']['App']['MTPUploadFiles'](arg1);
}

export function MTPUploadFilesWithStructure(arg1) {
  return window['go']['server']['App']['MTPUploadFilesWithStructure'](arg1);
}

export function MTPWalk(arg1) {
  return window['go']['server']['App']['MTPWalk'](arg1);
}

export function MarkNextPlaybackRemoteInitiated() {
  return window['go']['server']['App']['MarkNextPlaybackRemoteInitiated']();
}

export function NormalizeAnalyze(arg1) {
  return window['go']['server']['App']['NormalizeAnalyze'](arg1);
}

export function NormalizeApply(arg1) {
  return window['go']['server']['App']['NormalizeApply'](arg1);
}

export function NormalizeStartJob(arg1, arg2, arg3) {
  return window['go']['server']['App']['NormalizeStartJob'](arg1, arg2, arg3);
}

export function NotifyYouTubePlaybackState(arg1, arg2, arg3) {
  return window['go']['server']['App']['NotifyYouTubePlaybackState'](arg1, arg2, arg3);
}

export function Ping() {
  return window['go']['server']['App']['Ping']();
}

export function PrefetchSyncTracks(arg1) {
  return window['go']['server']['App']['PrefetchSyncTracks'](arg1);
}

export function PullSyncLibraryAssets(arg1, arg2) {
  return window['go']['server']['App']['PullSyncLibraryAssets'](arg1, arg2);
}

export function PushSyncLibraryAssets(arg1, arg2) {
  return window['go']['server']['App']['PushSyncLibraryAssets'](arg1, arg2);
}

export function PushSyncLibraryAssetsWithOptions(arg1, arg2, arg3) {
  return window['go']['server']['App']['PushSyncLibraryAssetsWithOptions'](arg1, arg2, arg3);
}

export function RefreshSyncRemoteCatalog() {
  return window['go']['server']['App']['RefreshSyncRemoteCatalog']();
}

export function RenamePlaylist(arg1) {
  return window['go']['server']['App']['RenamePlaylist'](arg1);
}

export function ReportEmbedPlaybackState(arg1, arg2, arg3) {
  return window['go']['server']['App']['ReportEmbedPlaybackState'](arg1, arg2, arg3);
}

export function RequestInitialLibrary() {
  return window['go']['server']['App']['RequestInitialLibrary']();
}

export function RequestPlaylistsWithArtwork() {
  return window['go']['server']['App']['RequestPlaylistsWithArtwork']();
}

export function ResolveYouTubeStreamURL(arg1) {
  return window['go']['server']['App']['ResolveYouTubeStreamURL'](arg1);
}

export function SaveAlbumSongOrder(arg1, arg2) {
  return window['go']['server']['App']['SaveAlbumSongOrder'](arg1, arg2);
}

export function SaveLrcFile(arg1, arg2) {
  return window['go']['server']['App']['SaveLrcFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['server']['App']['SaveSettings'](arg1);
}

export function ScanLibrary(arg1) {
  return window['go']['server']['App']['ScanLibrary'](arg1);
}

export function SearchTracksByMood(arg1, arg2) {
  return window['go']['server']['App']['SearchTracksByMood'](arg1, arg2);
}

export function SelectAndChangeAlbumArtwork(arg1) {
  return window['go']['server']['App']['SelectAndChangeAlbumArtwork'](arg1);
}

export function SelectFilesForNormalize() {
  return window['go']['server']['App']['SelectFilesForNormalize']();
}

export function SelectFolderForNormalize() {
  return window['go']['server']['App']['SelectFolderForNormalize']();
}

export function SelectMTPDownloadFolder() {
  return window['go']['server']['App']['SelectMTPDownloadFolder']();
}

export function SelectNormalizeOutputFolder() {
  return window['go']['server']['App']['SelectNormalizeOutputFolder']();
}

export function SetLibraryPath() {
  return window['go']['server']['App']['SetLibraryPath']();
}

export function SetLyricsSyncModelConsent(arg1) {
  return window['go']['server']['App']['SetLyricsSyncModelConsent'](arg1);
}

export function SetSidecarTargetDevice(arg1) {
  return window['go']['server']['App']['SetSidecarTargetDevice'](arg1);
}

export function SongFinished(arg1) {
  return window['go']['server']['App']['SongFinished'](arg1);
}

export function SongSkipped(arg1) {
  return window['go']['server']['App']['SongSkipped'](arg1);
}

export function StartDeviceWatcher() {
  return window['go']['server']['App']['StartDeviceWatcher']();
}

export function StartSyncPairing(arg1) {
  return window['go']['server']['App']['StartSyncPairing'](arg1);
}

export function StopDeviceWatcher() {
  return window['go']['server']['App']['StopDeviceWatcher']();
}

export function StopGemmaServer() {
  return window['go']['server']['App']['StopGemmaServer']();
}

export function UpdatePlaylistSongOrder(arg1) {
  return window['go']['server']['App']['UpdatePlaylistSongOrder'](arg1);
}
