// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAlbumToPlaylist(arg1) {
  return window['go']['server']['App']['AddAlbumToPlaylist'](arg1);
}

export function AddSongsToPlaylist(arg1) {
  return window['go']['server']['App']['AddSongsToPlaylist'](arg1);
}

export function AddYouTubeLink(arg1) {
  return window['go']['server']['App']['AddYouTubeLink'](arg1);
}

export function AudioGetCurrentDevice() {
  return window['go']['server']['App']['AudioGetCurrentDevice']();
}

export function AudioGetDuration() {
  return window['go']['server']['App']['AudioGetDuration']();
}

export function AudioGetFrequencyData() {
  return window['go']['server']['App']['AudioGetFrequencyData']();
}

export function AudioGetPosition() {
  return window['go']['server']['App']['AudioGetPosition']();
}

export function AudioGetStatus() {
  return window['go']['server']['App']['AudioGetStatus']();
}

export function AudioIsPaused() {
  return window['go']['server']['App']['AudioIsPaused']();
}

export function AudioIsPlaying() {
  return window['go']['server']['App']['AudioIsPlaying']();
}

export function AudioListDevices() {
  return window['go']['server']['App']['AudioListDevices']();
}

export function AudioPause() {
  return window['go']['server']['App']['AudioPause']();
}

export function AudioPlay(arg1, arg2) {
  return window['go']['server']['App']['AudioPlay'](arg1, arg2);
}

export function AudioResume() {
  return window['go']['server']['App']['AudioResume']();
}

export function AudioSeek(arg1) {
  return window['go']['server']['App']['AudioSeek'](arg1);
}

export function AudioSetDevice(arg1) {
  return window['go']['server']['App']['AudioSetDevice'](arg1);
}

export function AudioSetEqualizer(arg1) {
  return window['go']['server']['App']['AudioSetEqualizer'](arg1);
}

export function AudioSetNormalisationGain(arg1) {
  return window['go']['server']['App']['AudioSetNormalisationGain'](arg1);
}

export function AudioSetNowPlayingMetadata(arg1) {
  return window['go']['server']['App']['AudioSetNowPlayingMetadata'](arg1);
}

export function AudioSetVolume(arg1) {
  return window['go']['server']['App']['AudioSetVolume'](arg1);
}

export function AudioStop() {
  return window['go']['server']['App']['AudioStop']();
}

export function AutoSyncLyrics(arg1) {
  return window['go']['server']['App']['AutoSyncLyrics'](arg1);
}

export function BuildFLACIndexes() {
  return window['go']['server']['App']['BuildFLACIndexes']();
}

export function CDApplyMetadata(arg1) {
  return window['go']['server']['App']['CDApplyMetadata'](arg1);
}

export function CDScan() {
  return window['go']['server']['App']['CDScan']();
}

export function CDSearchTOC(arg1) {
  return window['go']['server']['App']['CDSearchTOC'](arg1);
}

export function CDSearchText(arg1) {
  return window['go']['server']['App']['CDSearchText'](arg1);
}

export function CDStartRip(arg1) {
  return window['go']['server']['App']['CDStartRip'](arg1);
}

export function CreatePlaylist(arg1) {
  return window['go']['server']['App']['CreatePlaylist'](arg1);
}

export function DeletePlaylist(arg1) {
  return window['go']['server']['App']['DeletePlaylist'](arg1);
}

export function DeleteSongs(arg1, arg2) {
  return window['go']['server']['App']['DeleteSongs'](arg1, arg2);
}

export function GetAllLoudnessData() {
  return window['go']['server']['App']['GetAllLoudnessData']();
}

export function GetAllPlaylists() {
  return window['go']['server']['App']['GetAllPlaylists']();
}

export function GetArtworkAsDataURL(arg1) {
  return window['go']['server']['App']['GetArtworkAsDataURL'](arg1);
}

export function GetArtworksDir() {
  return window['go']['server']['App']['GetArtworksDir']();
}

export function GetLibraryForNormalize() {
  return window['go']['server']['App']['GetLibraryForNormalize']();
}

export function GetLoudnessValue(arg1) {
  return window['go']['server']['App']['GetLoudnessValue'](arg1);
}

export function GetLyrics(arg1) {
  return window['go']['server']['App']['GetLyrics'](arg1);
}

export function GetMTPDevices() {
  return window['go']['server']['App']['GetMTPDevices']();
}

export function GetPerformanceSnapshot() {
  return window['go']['server']['App']['GetPerformanceSnapshot']();
}

export function GetPlaylistDetails(arg1) {
  return window['go']['server']['App']['GetPlaylistDetails'](arg1);
}

export function GetSettings() {
  return window['go']['server']['App']['GetSettings']();
}

export function GetSituationPlaylists() {
  return window['go']['server']['App']['GetSituationPlaylists']();
}

export function GetWearAddress() {
  return window['go']['server']['App']['GetWearAddress']();
}

export function GetWearPairingQRDataURL() {
  return window['go']['server']['App']['GetWearPairingQRDataURL']();
}

export function GetWearPairingURL() {
  return window['go']['server']['App']['GetWearPairingURL']();
}

export function GetYouTubeInfo(arg1) {
  return window['go']['server']['App']['GetYouTubeInfo'](arg1);
}

export function HandleLyricsDrop(arg1) {
  return window['go']['server']['App']['HandleLyricsDrop'](arg1);
}

export function IncrementPlayCount(arg1) {
  return window['go']['server']['App']['IncrementPlayCount'](arg1);
}

export function LoadLibrary() {
  return window['go']['server']['App']['LoadLibrary']();
}

export function LoadPlayCounts() {
  return window['go']['server']['App']['LoadPlayCounts']();
}

export function MTPDeleteFile(arg1) {
  return window['go']['server']['App']['MTPDeleteFile'](arg1);
}

export function MTPDispose() {
  return window['go']['server']['App']['MTPDispose']();
}

export function MTPDownloadFiles(arg1) {
  return window['go']['server']['App']['MTPDownloadFiles'](arg1);
}

export function MTPFetchDeviceInfo() {
  return window['go']['server']['App']['MTPFetchDeviceInfo']();
}

export function MTPFetchStorages() {
  return window['go']['server']['App']['MTPFetchStorages']();
}

export function MTPGetUntransferredSongs(arg1) {
  return window['go']['server']['App']['MTPGetUntransferredSongs'](arg1);
}

export function MTPInitialize() {
  return window['go']['server']['App']['MTPInitialize']();
}

export function MTPMakeDirectory(arg1) {
  return window['go']['server']['App']['MTPMakeDirectory'](arg1);
}

export function MTPUploadFiles(arg1) {
  return window['go']['server']['App']['MTPUploadFiles'](arg1);
}

export function MTPUploadFilesWithStructure(arg1) {
  return window['go']['server']['App']['MTPUploadFilesWithStructure'](arg1);
}

export function MTPWalk(arg1) {
  return window['go']['server']['App']['MTPWalk'](arg1);
}

export function NormalizeAnalyze(arg1) {
  return window['go']['server']['App']['NormalizeAnalyze'](arg1);
}

export function NormalizeApply(arg1) {
  return window['go']['server']['App']['NormalizeApply'](arg1);
}

export function NormalizeStartJob(arg1, arg2, arg3) {
  return window['go']['server']['App']['NormalizeStartJob'](arg1, arg2, arg3);
}

export function Ping() {
  return window['go']['server']['App']['Ping']();
}

export function RenamePlaylist(arg1) {
  return window['go']['server']['App']['RenamePlaylist'](arg1);
}

export function RequestInitialLibrary() {
  return window['go']['server']['App']['RequestInitialLibrary']();
}

export function RequestPlaylistsWithArtwork() {
  return window['go']['server']['App']['RequestPlaylistsWithArtwork']();
}

export function SaveAlbumSongOrder(arg1, arg2) {
  return window['go']['server']['App']['SaveAlbumSongOrder'](arg1, arg2);
}

export function SaveLrcFile(arg1, arg2) {
  return window['go']['server']['App']['SaveLrcFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['server']['App']['SaveSettings'](arg1);
}

export function ScanLibrary(arg1) {
  return window['go']['server']['App']['ScanLibrary'](arg1);
}

export function SelectAndChangeAlbumArtwork(arg1) {
  return window['go']['server']['App']['SelectAndChangeAlbumArtwork'](arg1);
}

export function SelectFilesForNormalize() {
  return window['go']['server']['App']['SelectFilesForNormalize']();
}

export function SelectFolderForNormalize() {
  return window['go']['server']['App']['SelectFolderForNormalize']();
}

export function SelectMTPDownloadFolder() {
  return window['go']['server']['App']['SelectMTPDownloadFolder']();
}

export function SelectNormalizeOutputFolder() {
  return window['go']['server']['App']['SelectNormalizeOutputFolder']();
}

export function SetLibraryPath() {
  return window['go']['server']['App']['SetLibraryPath']();
}

export function SongFinished(arg1) {
  return window['go']['server']['App']['SongFinished'](arg1);
}

export function SongSkipped(arg1) {
  return window['go']['server']['App']['SongSkipped'](arg1);
}

export function StartDeviceWatcher() {
  return window['go']['server']['App']['StartDeviceWatcher']();
}

export function StopDeviceWatcher() {
  return window['go']['server']['App']['StopDeviceWatcher']();
}

export function UpdatePlaylistSongOrder(arg1) {
  return window['go']['server']['App']['UpdatePlaylistSongOrder'](arg1);
}
