// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';
import {audio} from '../models';
import {lyricssync} from '../models';
import {cdrip} from '../models';
import {uxsync} from '../models';
import {moodspecial} from '../models';
import {mtp} from '../models';
import {normalize} from '../models';
import {scanner} from '../models';

export function AddAlbumToPlaylist(arg1:Record<string, any>):Promise<Record<string, any>>;

export function AddSongsToPlaylist(arg1:Record<string, any>):Promise<number>;

export function AddYouTubeLink(arg1:any):Promise<Record<string, any>>;

export function AnalyseLibraryAudioEmbeddings():Promise<server.AudioEmbedAnalyseResponse>;

export function AudioDebugOutputRMS():Promise<number>;

export function AudioGetCurrentDevice():Promise<string>;

export function AudioGetDuration():Promise<number>;

export function AudioGetFrequencyData():Promise<Array<number>>;

export function AudioGetPosition():Promise<number>;

export function AudioGetStatus():Promise<Record<string, any>>;

export function AudioIsPaused():Promise<boolean>;

export function AudioIsPlaying():Promise<boolean>;

export function AudioListDevices():Promise<Array<audio.Device>>;

export function AudioPause():Promise<void>;

export function AudioPlay(arg1:string,arg2:number):Promise<void>;

export function AudioResume():Promise<void>;

export function AudioSeek(arg1:number):Promise<void>;

export function AudioSetDevice(arg1:string):Promise<void>;

export function AudioSetEqualizer(arg1:server.AudioEqualizerSettings):Promise<void>;

export function AudioSetNormalisationGain(arg1:number):Promise<void>;

export function AudioSetNowPlayingMetadata(arg1:Record<string, any>):Promise<void>;

export function AudioSetVolume(arg1:number):Promise<void>;

export function AudioStartWebViewTap():Promise<void>;

export function AudioStop():Promise<void>;

export function AudioStopWebViewTap():Promise<void>;

export function AutoSyncLyrics(arg1:lyricssync.Request):Promise<lyricssync.Result>;

export function AutoSyncPairedDevices():Promise<server.SyncAutoResult>;

export function BuildFLACIndexes():Promise<void>;

export function CDApplyMetadata(arg1:Record<string, any>):Promise<cdrip.ReleaseInfo>;

export function CDApplyVocaDBMetadata(arg1:Record<string, any>):Promise<cdrip.ReleaseInfo>;

export function CDScan():Promise<Array<cdrip.Track>>;

export function CDSearchTOC(arg1:Array<cdrip.Track>):Promise<Array<cdrip.ReleaseInfo>>;

export function CDSearchText(arg1:string):Promise<Array<cdrip.ReleaseInfo>>;

export function CDSearchVocaDB(arg1:string):Promise<Array<cdrip.ReleaseInfo>>;

export function CDStartRip(arg1:Record<string, any>):Promise<any>;

export function ClearLyricsSyncModelCache():Promise<void>;

export function ConfirmSyncPairing(arg1:string,arg2:string,arg3:string,arg4:string):Promise<server.SyncPairingConfirmResult>;

export function CreatePlaylist(arg1:string):Promise<void>;

export function DeletePlaylist(arg1:string):Promise<void>;

export function DeleteSongs(arg1:Array<string>,arg2:boolean):Promise<Array<string>>;

export function DiscoverSyncDevices(arg1:number):Promise<Array<uxsync.MDNSPeer>>;

export function DownloadSyncTrack(arg1:string,arg2:string):Promise<server.SyncPullResult>;

export function EmbedDebugLog(arg1:string):Promise<void>;

export function GenerateMoodSpecial(arg1:string,arg2:number):Promise<moodspecial.Feature>;

export function GetAllLoudnessData():Promise<Record<string, any>>;

export function GetAllPlaylists():Promise<Array<string>>;

export function GetArtworkAsDataURL(arg1:string):Promise<string>;

export function GetArtworksDir():Promise<string>;

export function GetAudioEmbedStatus():Promise<server.AudioEmbedStatus>;

export function GetE2EEmbedVideoID():Promise<string>;

export function GetLANAddress():Promise<string>;

export function GetLibraryForNormalize():Promise<Array<any>>;

export function GetLoudnessValue(arg1:string):Promise<any>;

export function GetLyrics(arg1:string):Promise<any>;

export function GetLyricsSyncResourceStatus():Promise<Record<string, any>>;

export function GetMTPDevices():Promise<any>;

export function GetPairingQRDataURL():Promise<string>;

export function GetPairingURL():Promise<string>;

export function GetPerformanceSnapshot():Promise<server.PerformanceSnapshot>;

export function GetPlaylistDetails(arg1:string):Promise<any>;

export function GetSettings():Promise<any>;

export function GetSituationPlaylists():Promise<any>;

export function GetUnifiedLibrary():Promise<Record<string, any>>;

export function GetYouTubeEmbedLoudness(arg1:string):Promise<server.YouTubeEmbedLoudness>;

export function GetYouTubeEmbedURL(arg1:string):Promise<string>;

export function GetYouTubeInfo(arg1:string):Promise<any>;

export function HandleLyricsDrop(arg1:Array<string>):Promise<void>;

export function IncrementPlayCount(arg1:Record<string, any>):Promise<void>;

export function ListSyncDevices():Promise<Array<server.SyncDeviceRecord>>;

export function LoadLibrary():Promise<void>;

export function LoadPlayCounts():Promise<void>;

export function MTPDeleteFile(arg1:mtp.DeleteOptions):Promise<void>;

export function MTPDispose():Promise<void>;

export function MTPDownloadFiles(arg1:mtp.TransferOptions):Promise<void>;

export function MTPFetchDeviceInfo():Promise<Record<string, any>>;

export function MTPFetchStorages():Promise<Array<mtp.Storage>>;

export function MTPGetUntransferredSongs(arg1:Array<any>):Promise<Record<string, any>>;

export function MTPInitialize():Promise<void>;

export function MTPMakeDirectory(arg1:mtp.MakeDirOptions):Promise<void>;

export function MTPSelectDownloadFolder():Promise<string>;

export function MTPUploadFiles(arg1:mtp.TransferOptions):Promise<void>;

export function MTPUploadFilesWithStructure(arg1:Record<string, any>):Promise<Record<string, any>>;

export function MTPWalk(arg1:mtp.WalkOptions):Promise<any>;

export function NormalizeAnalyze(arg1:string):Promise<normalize.AnalysisResult>;

export function NormalizeApply(arg1:normalize.NormalizeJob):Promise<normalize.NormalizeResult>;

export function NormalizeStartJob(arg1:string,arg2:Array<any>,arg3:any):Promise<void>;

export function NotifyYouTubePlaybackState(arg1:boolean,arg2:string,arg3:string):Promise<void>;

export function Ping():Promise<string>;

export function PrefetchSyncTracks(arg1:Array<server.SyncTrackRef>):Promise<server.SyncPullResult>;

export function PullSyncLibraryAssets(arg1:string,arg2:number):Promise<server.SyncPullResult>;

export function PushSyncLibraryAssets(arg1:string,arg2:number):Promise<server.SyncPushResult>;

export function PushSyncLibraryAssetsWithOptions(arg1:string,arg2:number,arg3:server.SyncTransferOptions):Promise<server.SyncPushResult>;

export function RefreshSyncRemoteCatalog():Promise<void>;

export function RenamePlaylist(arg1:Record<string, any>):Promise<void>;

export function RequestInitialLibrary():Promise<void>;

export function RequestPlaylistsWithArtwork():Promise<void>;

export function ResolveYouTubeStreamURL(arg1:string):Promise<string>;

export function SaveAlbumSongOrder(arg1:string,arg2:Array<string>):Promise<void>;

export function SaveLrcFile(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:any):Promise<void>;

export function ScanLibrary(arg1:Array<string>):Promise<scanner.ScanResult>;

export function SearchTracksByMood(arg1:string,arg2:number):Promise<Array<server.AudioEmbedSearchHit>>;

export function SelectAndChangeAlbumArtwork(arg1:string):Promise<void>;

export function SelectFilesForNormalize():Promise<Array<string>>;

export function SelectFolderForNormalize():Promise<Array<string>>;

export function SelectMTPDownloadFolder():Promise<string>;

export function SelectNormalizeOutputFolder():Promise<string>;

export function SetLibraryPath():Promise<string>;

export function SetLyricsSyncModelConsent(arg1:boolean):Promise<void>;

export function SongFinished(arg1:Record<string, any>):Promise<void>;

export function SongSkipped(arg1:Record<string, any>):Promise<void>;

export function StartDeviceWatcher():Promise<void>;

export function StartSyncPairing(arg1:string):Promise<server.SyncPairingStartResult>;

export function StopDeviceWatcher():Promise<void>;

export function StopGemmaServer():Promise<void>;

export function UpdatePlaylistSongOrder(arg1:Record<string, any>):Promise<void>;
