// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAlbumToPlaylist(arg1:Record<string, any>):Promise<Record<string, any>>;

export function AddSongsToPlaylist(arg1:Record<string, any>):Promise<number>;

export function CDApplyMetadata(arg1:any,arg2:string):Promise<any>;

export function CDScan():Promise<any>;

export function CDSearchTOC(arg1:any):Promise<any>;

export function CDSearchText(arg1:string):Promise<any>;

export function CDStartRip(arg1:any,arg2:any):Promise<any>;

export function CreatePlaylist(arg1:string):Promise<void>;

export function DeletePlaylist(arg1:string):Promise<void>;

export function GetAllPlaylists():Promise<Array<string>>;

export function GetArtworkAsDataURL(arg1:string):Promise<string>;

export function GetArtworksDir():Promise<string>;

export function GetLoudnessValue(arg1:string):Promise<any>;

export function GetLyrics(arg1:string):Promise<any>;

export function GetPlaylistDetails(arg1:string):Promise<any>;

export function GetSettings():Promise<any>;

export function GetSituationPlaylists():Promise<any>;

export function GetYouTubeInfo(arg1:string):Promise<any>;

export function HandleLyricsDrop(arg1:Array<string>):Promise<void>;

export function IncrementPlayCount(arg1:Record<string, any>):Promise<void>;

export function LoadLibrary():Promise<void>;

export function LoadPlayCounts():Promise<void>;

export function Ping():Promise<string>;

export function RenamePlaylist(arg1:Record<string, any>):Promise<void>;

export function RequestInitialLibrary():Promise<void>;

export function RequestPlaylistsWithArtwork():Promise<void>;

export function SaveLrcFile(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:any):Promise<void>;

export function ScanLibrary(arg1:Array<string>):Promise<main.ScanResult>;

export function SongFinished(arg1:Record<string, any>):Promise<void>;

export function SongSkipped(arg1:Record<string, any>):Promise<void>;

export function UpdatePlaylistSongOrder(arg1:Record<string, any>):Promise<void>;
