// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAlbumToPlaylist(arg1) {
  return window['go']['main']['App']['AddAlbumToPlaylist'](arg1);
}

export function AddSongsToPlaylist(arg1) {
  return window['go']['main']['App']['AddSongsToPlaylist'](arg1);
}

export function CreatePlaylist(arg1) {
  return window['go']['main']['App']['CreatePlaylist'](arg1);
}

export function DeletePlaylist(arg1) {
  return window['go']['main']['App']['DeletePlaylist'](arg1);
}

export function GetAllPlaylists() {
  return window['go']['main']['App']['GetAllPlaylists']();
}

export function GetArtworkAsDataURL(arg1) {
  return window['go']['main']['App']['GetArtworkAsDataURL'](arg1);
}

export function GetArtworksDir() {
  return window['go']['main']['App']['GetArtworksDir']();
}

export function GetLoudnessValue(arg1) {
  return window['go']['main']['App']['GetLoudnessValue'](arg1);
}

export function GetLyrics(arg1) {
  return window['go']['main']['App']['GetLyrics'](arg1);
}

export function GetPlaylistDetails(arg1) {
  return window['go']['main']['App']['GetPlaylistDetails'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSituationPlaylists() {
  return window['go']['main']['App']['GetSituationPlaylists']();
}

export function GetYouTubeInfo(arg1) {
  return window['go']['main']['App']['GetYouTubeInfo'](arg1);
}

export function HandleLyricsDrop(arg1) {
  return window['go']['main']['App']['HandleLyricsDrop'](arg1);
}

export function LoadLibrary() {
  return window['go']['main']['App']['LoadLibrary']();
}

export function LoadPlayCounts() {
  return window['go']['main']['App']['LoadPlayCounts']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RenamePlaylist(arg1) {
  return window['go']['main']['App']['RenamePlaylist'](arg1);
}

export function RequestInitialLibrary() {
  return window['go']['main']['App']['RequestInitialLibrary']();
}

export function RequestPlaylistsWithArtwork() {
  return window['go']['main']['App']['RequestPlaylistsWithArtwork']();
}

export function SaveLrcFile(arg1, arg2) {
  return window['go']['main']['App']['SaveLrcFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanLibrary(arg1) {
  return window['go']['main']['App']['ScanLibrary'](arg1);
}

export function UpdatePlaylistSongOrder(arg1) {
  return window['go']['main']['App']['UpdatePlaylistSongOrder'](arg1);
}
