// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetYouTubeInfo(arg1) {
  return window['go']['main']['App']['GetYouTubeInfo'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function ScanLibrary(arg1) {
  return window['go']['main']['App']['ScanLibrary'](arg1);
}
