// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAlbumToPlaylist(arg1) {
  return window['go']['main']['App']['AddAlbumToPlaylist'](arg1);
}

export function AddSongsToPlaylist(arg1) {
  return window['go']['main']['App']['AddSongsToPlaylist'](arg1);
}

export function AudioGetCurrentDevice() {
  return window['go']['main']['App']['AudioGetCurrentDevice']();
}

export function AudioGetDuration() {
  return window['go']['main']['App']['AudioGetDuration']();
}

export function AudioGetFrequencyData() {
  return window['go']['main']['App']['AudioGetFrequencyData']();
}

export function AudioGetPosition() {
  return window['go']['main']['App']['AudioGetPosition']();
}

export function AudioIsPaused() {
  return window['go']['main']['App']['AudioIsPaused']();
}

export function AudioIsPlaying() {
  return window['go']['main']['App']['AudioIsPlaying']();
}

export function AudioListDevices() {
  return window['go']['main']['App']['AudioListDevices']();
}

export function AudioPause() {
  return window['go']['main']['App']['AudioPause']();
}

export function AudioPlay(arg1) {
  return window['go']['main']['App']['AudioPlay'](arg1);
}

export function AudioResume() {
  return window['go']['main']['App']['AudioResume']();
}

export function AudioSeek(arg1) {
  return window['go']['main']['App']['AudioSeek'](arg1);
}

export function AudioSetDevice(arg1) {
  return window['go']['main']['App']['AudioSetDevice'](arg1);
}

export function AudioSetVolume(arg1) {
  return window['go']['main']['App']['AudioSetVolume'](arg1);
}

export function AudioStop() {
  return window['go']['main']['App']['AudioStop']();
}

export function BuildFLACIndexes() {
  return window['go']['main']['App']['BuildFLACIndexes']();
}

export function CDApplyMetadata(arg1) {
  return window['go']['main']['App']['CDApplyMetadata'](arg1);
}

export function CDScan() {
  return window['go']['main']['App']['CDScan']();
}

export function CDSearchTOC(arg1) {
  return window['go']['main']['App']['CDSearchTOC'](arg1);
}

export function CDSearchText(arg1) {
  return window['go']['main']['App']['CDSearchText'](arg1);
}

export function CDStartRip(arg1) {
  return window['go']['main']['App']['CDStartRip'](arg1);
}

export function CreatePlaylist(arg1) {
  return window['go']['main']['App']['CreatePlaylist'](arg1);
}

export function DeletePlaylist(arg1) {
  return window['go']['main']['App']['DeletePlaylist'](arg1);
}

export function GetAllPlaylists() {
  return window['go']['main']['App']['GetAllPlaylists']();
}

export function GetArtworkAsDataURL(arg1) {
  return window['go']['main']['App']['GetArtworkAsDataURL'](arg1);
}

export function GetArtworksDir() {
  return window['go']['main']['App']['GetArtworksDir']();
}

export function GetLoudnessValue(arg1) {
  return window['go']['main']['App']['GetLoudnessValue'](arg1);
}

export function GetLyrics(arg1) {
  return window['go']['main']['App']['GetLyrics'](arg1);
}

export function GetMTPDevices() {
  return window['go']['main']['App']['GetMTPDevices']();
}

export function GetPlaylistDetails(arg1) {
  return window['go']['main']['App']['GetPlaylistDetails'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSituationPlaylists() {
  return window['go']['main']['App']['GetSituationPlaylists']();
}

export function GetYouTubeInfo(arg1) {
  return window['go']['main']['App']['GetYouTubeInfo'](arg1);
}

export function HandleLyricsDrop(arg1) {
  return window['go']['main']['App']['HandleLyricsDrop'](arg1);
}

export function IncrementPlayCount(arg1) {
  return window['go']['main']['App']['IncrementPlayCount'](arg1);
}

export function LoadLibrary() {
  return window['go']['main']['App']['LoadLibrary']();
}

export function LoadPlayCounts() {
  return window['go']['main']['App']['LoadPlayCounts']();
}

export function MTPDeleteFile(arg1) {
  return window['go']['main']['App']['MTPDeleteFile'](arg1);
}

export function MTPDispose() {
  return window['go']['main']['App']['MTPDispose']();
}

export function MTPDownloadFiles(arg1) {
  return window['go']['main']['App']['MTPDownloadFiles'](arg1);
}

export function MTPFetchDeviceInfo() {
  return window['go']['main']['App']['MTPFetchDeviceInfo']();
}

export function MTPFetchStorages() {
  return window['go']['main']['App']['MTPFetchStorages']();
}

export function MTPGetUntransferredSongs(arg1) {
  return window['go']['main']['App']['MTPGetUntransferredSongs'](arg1);
}

export function MTPInitialize() {
  return window['go']['main']['App']['MTPInitialize']();
}

export function MTPMakeDirectory(arg1) {
  return window['go']['main']['App']['MTPMakeDirectory'](arg1);
}

export function MTPUploadFiles(arg1) {
  return window['go']['main']['App']['MTPUploadFiles'](arg1);
}

export function MTPUploadFilesWithStructure(arg1) {
  return window['go']['main']['App']['MTPUploadFilesWithStructure'](arg1);
}

export function MTPWalk(arg1) {
  return window['go']['main']['App']['MTPWalk'](arg1);
}

export function NormalizeAnalyze(arg1) {
  return window['go']['main']['App']['NormalizeAnalyze'](arg1);
}

export function NormalizeApply(arg1) {
  return window['go']['main']['App']['NormalizeApply'](arg1);
}

export function NormalizeStartJob(arg1, arg2, arg3) {
  return window['go']['main']['App']['NormalizeStartJob'](arg1, arg2, arg3);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RenamePlaylist(arg1) {
  return window['go']['main']['App']['RenamePlaylist'](arg1);
}

export function RequestInitialLibrary() {
  return window['go']['main']['App']['RequestInitialLibrary']();
}

export function RequestPlaylistsWithArtwork() {
  return window['go']['main']['App']['RequestPlaylistsWithArtwork']();
}

export function SaveLrcFile(arg1, arg2) {
  return window['go']['main']['App']['SaveLrcFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanLibrary(arg1) {
  return window['go']['main']['App']['ScanLibrary'](arg1);
}

export function SongFinished(arg1) {
  return window['go']['main']['App']['SongFinished'](arg1);
}

export function SongSkipped(arg1) {
  return window['go']['main']['App']['SongSkipped'](arg1);
}

export function UpdatePlaylistSongOrder(arg1) {
  return window['go']['main']['App']['UpdatePlaylistSongOrder'](arg1);
}
