// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetArtworksDir():Promise<string>;

export function GetSettings():Promise<any>;

export function GetYouTubeInfo(arg1:string):Promise<any>;

export function LoadLibrary():Promise<void>;

export function LoadPlayCounts():Promise<void>;

export function Ping():Promise<string>;

export function RequestInitialLibrary():Promise<void>;

export function SaveSettings(arg1:any):Promise<void>;

export function ScanLibrary(arg1:Array<string>):Promise<main.ScanResult>;
