// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audio} from '../models';
import {main} from '../models';
import {lyricssync} from '../models';
import {cdrip} from '../models';
import {mtp} from '../models';
import {normalize} from '../models';
import {scanner} from '../models';

export function AddAlbumToPlaylist(arg1:Record<string, any>):Promise<Record<string, any>>;

export function AddSongsToPlaylist(arg1:Record<string, any>):Promise<number>;

export function AddYouTubeLink(arg1:any):Promise<Record<string, any>>;

export function AudioGetCurrentDevice():Promise<string>;

export function AudioGetDuration():Promise<number>;

export function AudioGetFrequencyData():Promise<Array<number>>;

export function AudioGetPosition():Promise<number>;

export function AudioGetStatus():Promise<Record<string, any>>;

export function AudioIsPaused():Promise<boolean>;

export function AudioIsPlaying():Promise<boolean>;

export function AudioListDevices():Promise<Array<audio.Device>>;

export function AudioPause():Promise<void>;

export function AudioPlay(arg1:string):Promise<void>;

export function AudioResume():Promise<void>;

export function AudioSeek(arg1:number):Promise<void>;

export function AudioSetDevice(arg1:string):Promise<void>;

export function AudioSetEqualizer(arg1:main.AudioEqualizerSettings):Promise<void>;

export function AudioSetNowPlayingMetadata(arg1:Record<string, any>):Promise<void>;

export function AudioSetVolume(arg1:number):Promise<void>;

export function AudioStop():Promise<void>;

export function AutoSyncLyrics(arg1:lyricssync.Request):Promise<lyricssync.Result>;

export function BuildFLACIndexes():Promise<void>;

export function CDApplyMetadata(arg1:Record<string, any>):Promise<cdrip.ReleaseInfo>;

export function CDScan():Promise<Array<cdrip.Track>>;

export function CDSearchTOC(arg1:Array<cdrip.Track>):Promise<Array<cdrip.ReleaseInfo>>;

export function CDSearchText(arg1:string):Promise<Array<cdrip.ReleaseInfo>>;

export function CDStartRip(arg1:Record<string, any>):Promise<any>;

export function CreatePlaylist(arg1:string):Promise<void>;

export function DeletePlaylist(arg1:string):Promise<void>;

export function DeleteSongs(arg1:Array<string>,arg2:boolean):Promise<Array<string>>;

export function GetAllLoudnessData():Promise<Record<string, any>>;

export function GetAllPlaylists():Promise<Array<string>>;

export function GetArtworkAsDataURL(arg1:string):Promise<string>;

export function GetArtworksDir():Promise<string>;

export function GetLibraryForNormalize():Promise<Array<any>>;

export function GetLoudnessValue(arg1:string):Promise<any>;

export function GetLyrics(arg1:string):Promise<any>;

export function GetMTPDevices():Promise<any>;

export function GetPerformanceSnapshot():Promise<main.PerformanceSnapshot>;

export function GetPlaylistDetails(arg1:string):Promise<any>;

export function GetSettings():Promise<any>;

export function GetSituationPlaylists():Promise<any>;

export function GetWearAddress():Promise<string>;

export function GetYouTubeInfo(arg1:string):Promise<any>;

export function HandleLyricsDrop(arg1:Array<string>):Promise<void>;

export function IncrementPlayCount(arg1:Record<string, any>):Promise<void>;

export function LoadLibrary():Promise<void>;

export function LoadPlayCounts():Promise<void>;

export function MTPDeleteFile(arg1:mtp.DeleteOptions):Promise<void>;

export function MTPDispose():Promise<void>;

export function MTPDownloadFiles(arg1:mtp.TransferOptions):Promise<void>;

export function MTPFetchDeviceInfo():Promise<Record<string, any>>;

export function MTPFetchStorages():Promise<Array<mtp.Storage>>;

export function MTPGetUntransferredSongs(arg1:Array<any>):Promise<Record<string, any>>;

export function MTPInitialize():Promise<void>;

export function MTPMakeDirectory(arg1:mtp.MakeDirOptions):Promise<void>;

export function MTPUploadFiles(arg1:mtp.TransferOptions):Promise<void>;

export function MTPUploadFilesWithStructure(arg1:Record<string, any>):Promise<Record<string, any>>;

export function MTPWalk(arg1:mtp.WalkOptions):Promise<any>;

export function NormalizeAnalyze(arg1:string):Promise<normalize.AnalysisResult>;

export function NormalizeApply(arg1:normalize.NormalizeJob):Promise<normalize.NormalizeResult>;

export function NormalizeStartJob(arg1:string,arg2:Array<any>,arg3:any):Promise<void>;

export function Ping():Promise<string>;

export function RenamePlaylist(arg1:Record<string, any>):Promise<void>;

export function RequestInitialLibrary():Promise<void>;

export function RequestPlaylistsWithArtwork():Promise<void>;

export function SaveLrcFile(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:any):Promise<void>;

export function ScanLibrary(arg1:Array<string>):Promise<scanner.ScanResult>;

export function SelectFilesForNormalize():Promise<Array<string>>;

export function SelectFolderForNormalize():Promise<Array<string>>;

export function SelectNormalizeOutputFolder():Promise<string>;

export function SetLibraryPath():Promise<string>;

export function SongFinished(arg1:Record<string, any>):Promise<void>;

export function SongSkipped(arg1:Record<string, any>):Promise<void>;

export function StartDeviceWatcher():Promise<void>;

export function StopDeviceWatcher():Promise<void>;

export function UpdatePlaylistSongOrder(arg1:Record<string, any>):Promise<void>;
