import Foundation
import MediaPlayer

/// Pure queue-navigation arithmetic shared by the Watch player service and its tests. Kept free of
/// `AVPlayer`/WatchKit so the wrap-around and "restart vs. skip back" rules are unit-testable
/// without a real playback session.
///
/// This type has iOS and watchOS target membership, mirroring `WatchTransfer.swift`.
enum WatchQueueNavigation {
    /// Index of the next track, wrapping to the start of the queue. `0` when the queue is empty
    /// (caller is expected to guard on `count == 0` separately if that should be a no-op).
    static func nextIndex(current: Int, count: Int) -> Int {
        guard count > 0 else { return 0 }
        return (current + 1) % count
    }

    /// Index of the previous track, wrapping to the end of the queue.
    static func previousIndex(current: Int, count: Int) -> Int {
        guard count > 0 else { return 0 }
        return (current - 1 + count) % count
    }

    /// Standard media-player UX: pressing "previous" more than `threshold` seconds into a track
    /// restarts the current track instead of jumping back a track.
    static func shouldRestartOnPrevious(position: Double, threshold: Double = 3) -> Bool {
        position > threshold
    }

    /// What should happen when the current track finishes playing naturally, given `repeatMode`.
    /// Unlike `nextIndex` (used for the manual "skip forward" button, which always wraps), this
    /// stops playback at the end of the queue when repeat is off — matching classic Walkman/media
    /// player behaviour instead of silently looping forever.
    static func autoAdvance(current: Int, count: Int, repeatMode: WatchRepeatMode) -> WatchAutoAdvanceResult {
        guard count > 0 else { return .stop }
        switch repeatMode {
        case .one:
            return .index(current)
        case .all:
            return .index(nextIndex(current: current, count: count))
        case .off:
            let next = current + 1
            return next < count ? .index(next) : .stop
        }
    }
}

/// Outcome of `WatchQueueNavigation.autoAdvance`: either move to another index, or stop playback
/// because the queue has been exhausted with repeat off.
enum WatchAutoAdvanceResult: Equatable {
    case index(Int)
    case stop
}

/// Explicit repeat state for the Watch player (previously an implicit "always loop the queue").
/// `next()` cycles through the three states in the order a physical Walkman's repeat button would:
/// off → all → one → off.
enum WatchRepeatMode: String, Codable, Equatable, CaseIterable {
    case off
    case all
    case one

    func next() -> WatchRepeatMode {
        switch self {
        case .off: return .all
        case .all: return .one
        case .one: return .off
        }
    }

    var systemImageName: String {
        switch self {
        case .off: return "repeat"
        case .all: return "repeat"
        case .one: return "repeat.1"
        }
    }
}

/// Pure reordering for shuffle mode. The random permutation itself is generated by the caller
/// (`Array.shuffled()` at the call site) so this function stays deterministic and unit-testable;
/// it only handles the "keep the currently-playing song first" rule, matching classic media-player
/// shuffle UX where turning shuffle on never interrupts what is currently playing.
enum WatchShuffleLogic {
    /// Reorders `queue` according to `shuffledIndices` (expected to be a permutation of
    /// `queue.indices`), then moves the song matching `currentId` to the front. Returns `queue`
    /// unchanged if `shuffledIndices` does not match `queue`'s count (defensive — should not
    /// happen given well-behaved callers).
    static func applyShuffle(
        queue: [WatchTransferMeta],
        shuffledIndices: [Int],
        currentId: String?
    ) -> [WatchTransferMeta] {
        guard shuffledIndices.count == queue.count else { return queue }
        var shuffled = shuffledIndices.map { queue[$0] }
        guard let currentId, let index = shuffled.firstIndex(where: { $0.id == currentId }) else {
            return shuffled
        }
        let current = shuffled.remove(at: index)
        shuffled.insert(current, at: 0)
        return shuffled
    }
}

/// Persisted "where were we" snapshot so the Watch app can restore the last song, position, queue
/// order, and mode after a relaunch — without auto-starting playback (a cold-launch loading a fresh
/// `AVPlayer` for the last-played song and immediately blasting audio would be a bad surprise).
struct WatchPlaybackResumeState: Codable, Equatable {
    var songId: String
    var position: Double
    /// The queue as it was actually playing (post-shuffle, if shuffled).
    var queueSongIds: [String]
    /// The queue in its original (un-shuffled) order, so turning shuffle back off can restore it.
    var originalQueueSongIds: [String]
    var currentIndex: Int
    var repeatMode: WatchRepeatMode
    var isShuffled: Bool
}

/// Pure helpers for turning a `WatchPlaybackResumeState` back into a live queue against whatever
/// songs are actually present in the library at launch (a song may have been deleted since the
/// state was saved).
enum WatchResumeLogic {
    /// Resolves a list of song ids against the current library, preserving `ids`' order and
    /// silently dropping ids that no longer exist locally.
    static func resolveSongs(ids: [String], librarySongs: [WatchTransferMeta]) -> [WatchTransferMeta] {
        let byId = Dictionary(uniqueKeysWithValues: librarySongs.map { ($0.id, $0) })
        return ids.compactMap { byId[$0] }
    }

    /// Index of the song matching `songId` within `queue`, if still present.
    static func resumeIndex(songId: String, queue: [WatchTransferMeta]) -> Int? {
        queue.firstIndex(where: { $0.id == songId })
    }
}

/// Pure clamping for Digital Crown-driven seeking, so the "never seek past the ends of the track"
/// rule is unit-testable independent of `AVPlayer`.
enum WatchSeekLogic {
    /// Clamps a raw seek target (e.g. from `.digitalCrownRotation`) to `0...duration`. Returns `0`
    /// for a non-positive duration (nothing sensible to seek to).
    static func clampedPosition(_ raw: Double, duration: Double) -> Double {
        guard duration > 0 else { return 0 }
        return min(max(raw, 0), duration)
    }
}

/// Builds the `MPNowPlayingInfoCenter` payload from Watch playback state, kept as a pure function so
/// the key/value mapping is unit-testable without `MPNowPlayingInfoCenter.default()` (which cannot
/// be observed from an XCTest target).
enum WatchNowPlayingInfoBuilder {
    static func buildInfo(for song: WatchTransferMeta?, isPlaying: Bool, position: Double) -> [String: Any] {
        guard let song else { return [:] }
        return [
            MPMediaItemPropertyTitle: song.displayTitle,
            MPMediaItemPropertyArtist: song.displayArtist,
            MPMediaItemPropertyAlbumTitle: song.displayAlbum,
            MPMediaItemPropertyPlaybackDuration: song.duration,
            MPNowPlayingInfoPropertyElapsedPlaybackTime: position,
            MPNowPlayingInfoPropertyPlaybackRate: isPlaying ? 1.0 : 0.0
        ]
    }
}
