import Foundation
import MediaPlayer

/// Pure queue-navigation arithmetic shared by the Watch player service, `MusicPlayerService`
/// (the iPhone-local player), and their tests. Kept free of `AVPlayer`/WatchKit so the wrap-around
/// and "restart vs. skip back" rules are unit-testable without a real playback session.
///
/// Originally Watch-only (hence the historic `Watch*` names, kept below as `typealias` shims so
/// `WatchPlaybackLogicTests.swift` and the watchOS target keep compiling unchanged); generalised so
/// `MusicPlayerService` can share the same shuffle/repeat/auto-advance rules instead of the
/// always-loop `(currentIndex + 1) % queue.count` it used to hard-code.
///
/// This type has iOS and watchOS target membership, mirroring `WatchTransfer.swift`.
enum PlaybackQueueNavigation {
    /// Index of the next track, wrapping to the start of the queue. `0` when the queue is empty
    /// (caller is expected to guard on `count == 0` separately if that should be a no-op).
    static func nextIndex(current: Int, count: Int) -> Int {
        guard count > 0 else { return 0 }
        return (current + 1) % count
    }

    /// Index of the previous track, wrapping to the end of the queue.
    static func previousIndex(current: Int, count: Int) -> Int {
        guard count > 0 else { return 0 }
        return (current - 1 + count) % count
    }

    /// Standard media-player UX: pressing "previous" more than `threshold` seconds into a track
    /// restarts the current track instead of jumping back a track.
    static func shouldRestartOnPrevious(position: Double, threshold: Double = 3) -> Bool {
        position > threshold
    }

    /// What should happen when the current track finishes playing naturally, given `repeatMode`.
    /// Unlike `nextIndex` (used for the manual "skip forward" button, which always wraps), this
    /// stops playback at the end of the queue when repeat is off — matching classic Walkman/media
    /// player behaviour instead of silently looping forever.
    static func autoAdvance(current: Int, count: Int, repeatMode: PlaybackRepeatMode) -> PlaybackAutoAdvanceResult {
        guard count > 0 else { return .stop }
        switch repeatMode {
        case .one:
            return .index(current)
        case .all:
            return .index(nextIndex(current: current, count: count))
        case .off:
            let next = current + 1
            return next < count ? .index(next) : .stop
        }
    }
}

/// Outcome of `PlaybackQueueNavigation.autoAdvance`: either move to another index, or stop playback
/// because the queue has been exhausted with repeat off.
enum PlaybackAutoAdvanceResult: Equatable {
    case index(Int)
    case stop
}

/// Explicit repeat state for a player (previously an implicit "always loop the queue" on the
/// iPhone-local player). `next()` cycles through the three states in the order a physical Walkman's
/// repeat button would: off → all → one → off.
enum PlaybackRepeatMode: String, Codable, Equatable, CaseIterable {
    case off
    case all
    case one

    func next() -> PlaybackRepeatMode {
        switch self {
        case .off: return .all
        case .all: return .one
        case .one: return .off
        }
    }

    var systemImageName: String {
        switch self {
        case .off: return "repeat"
        case .all: return "repeat"
        case .one: return "repeat.1"
        }
    }
}

/// Pure reordering for shuffle mode. The random permutation itself is generated by the caller
/// (`Array.shuffled()` at the call site) so this function stays deterministic and unit-testable;
/// it only handles the "keep the currently-playing song first" rule, matching classic media-player
/// shuffle UX where turning shuffle on never interrupts what is currently playing.
enum PlaybackShuffleLogic {
    // The `[WatchTransferMeta]` overload is Watch-only (that type lives in `WatchTransfer.swift`,
    // not shared with tvOS); the `[Song]` overload used by `MusicPlayerService` on tvOS lives in
    // `PlaybackQueueEditing.swift` instead. Excluded here rather than pulling `WatchTransfer.swift`
    // (and its own dependency graph) into the TV target for a shuffle helper it never calls.
    #if !os(tvOS)
    /// Reorders `queue` according to `shuffledIndices` (expected to be a permutation of
    /// `queue.indices`), then moves the song matching `currentId` to the front. Returns `queue`
    /// unchanged if `shuffledIndices` does not match `queue`'s count (defensive — should not
    /// happen given well-behaved callers).
    static func applyShuffle(
        queue: [WatchTransferMeta],
        shuffledIndices: [Int],
        currentId: String?
    ) -> [WatchTransferMeta] {
        guard shuffledIndices.count == queue.count else { return queue }
        var shuffled = shuffledIndices.map { queue[$0] }
        guard let currentId, let index = shuffled.firstIndex(where: { $0.id == currentId }) else {
            return shuffled
        }
        let current = shuffled.remove(at: index)
        shuffled.insert(current, at: 0)
        return shuffled
    }
    #endif
}

// MARK: - Backwards-compatible names
//
// The types above were generalised from Watch-only to shared iOS/watchOS playback logic (see the
// doc comment on `PlaybackQueueNavigation`). These aliases keep `WatchPlaybackLogicTests.swift` and
// any watchOS-side call sites compiling unchanged.
typealias WatchQueueNavigation = PlaybackQueueNavigation
typealias WatchAutoAdvanceResult = PlaybackAutoAdvanceResult
typealias WatchRepeatMode = PlaybackRepeatMode
typealias WatchShuffleLogic = PlaybackShuffleLogic

/// Persisted "where were we" snapshot so the Watch app can restore the last song, position, queue
/// order, and mode after a relaunch — without auto-starting playback (a cold-launch loading a fresh
/// `AVPlayer` for the last-played song and immediately blasting audio would be a bad surprise).
struct WatchPlaybackResumeState: Codable, Equatable {
    var songId: String
    var position: Double
    /// The queue as it was actually playing (post-shuffle, if shuffled).
    var queueSongIds: [String]
    /// The queue in its original (un-shuffled) order, so turning shuffle back off can restore it.
    var originalQueueSongIds: [String]
    var currentIndex: Int
    var repeatMode: WatchRepeatMode
    var isShuffled: Bool
}

// The remainder of this file (`WatchResumeLogic` onward) is Watch-app-specific: it works in terms
// of `WatchTransferMeta`/`AlbumGroupPosition` (defined in `WatchTransfer.swift`/
// `AlbumGroupPosition.swift`, not shared with tvOS — see `progress/tvos-target.md`). Only the
// queue-navigation/repeat/shuffle logic above is shared with `MusicPlayerService` on tvOS, so it
// is excluded there rather than pulling the whole Watch transfer-metadata type graph into the TV
// target for no reason.
#if !os(tvOS)

/// Pure helpers for turning a `WatchPlaybackResumeState` back into a live queue against whatever
/// songs are actually present in the library at launch (a song may have been deleted since the
/// state was saved).
enum WatchResumeLogic {
    /// Resolves a list of song ids against the current library, preserving `ids`' order and
    /// silently dropping ids that no longer exist locally.
    static func resolveSongs(ids: [String], librarySongs: [WatchTransferMeta]) -> [WatchTransferMeta] {
        let byId = Dictionary(uniqueKeysWithValues: librarySongs.map { ($0.id, $0) })
        return ids.compactMap { byId[$0] }
    }

    /// Index of the song matching `songId` within `queue`, if still present.
    static func resumeIndex(songId: String, queue: [WatchTransferMeta]) -> Int? {
        queue.firstIndex(where: { $0.id == songId })
    }
}

/// Pure clamping for Digital Crown-driven seeking, so the "never seek past the ends of the track"
/// rule is unit-testable independent of `AVPlayer`.
enum WatchSeekLogic {
    /// Clamps a raw seek target (e.g. from `.digitalCrownRotation`) to `0...duration`. Returns `0`
    /// for a non-positive duration (nothing sensible to seek to).
    static func clampedPosition(_ raw: Double, duration: Double) -> Double {
        guard duration > 0 else { return 0 }
        return min(max(raw, 0), duration)
    }
}

/// One album's worth of songs, grouped for the Watch's "Albums" browse mode (see
/// `WatchAlbumGrouping`). `songs` is sorted into track order by `WatchAlbumGrouping.albums(from:)`
/// (disc, then track, then arrival order for songs with no number) — songs are *not* guaranteed to
/// arrive from the iPhone in track order (on-device transcoding can finish, and therefore
/// `transferFile`, out of enqueue order), so the sort is load-bearing, not cosmetic.
struct WatchAlbumGroup: Identifiable, Equatable {
    var id: String { album }
    var album: String
    var songs: [WatchTransferMeta]

    /// The song whose artwork represents this album in the album list (simply the first song —
    /// good enough since most albums share one piece of artwork across all tracks).
    var artworkSong: WatchTransferMeta? { songs.first }
}

/// Pure grouping of a flat song list into per-album buckets, kept free of any Watch UI/storage
/// dependency so the "how do songs collapse into albums" rule is unit-testable on its own. Used by
/// `WatchSongListView`'s "Albums" browse mode alongside the existing flat "Songs" list.
enum WatchAlbumGrouping {
    /// Groups `songs` by `displayAlbum` (so a blank album field collapses to "Unknown Album"
    /// rather than splintering into its own blank-named group), preserving the order albums first
    /// appear in `songs`, then sorts the resulting albums alphabetically for browsing. Within each
    /// album, songs are sorted into track order (disc, then track number; songs missing a number
    /// sort after numbered ones and keep their relative arrival order — see `sortedByTrackOrder`)
    /// rather than kept in arrival order, since arrival order is not reliably track order (see
    /// `WatchAlbumGroup`'s doc comment).
    static func albums(from songs: [WatchTransferMeta]) -> [WatchAlbumGroup] {
        var order: [String] = []
        var buckets: [String: [WatchTransferMeta]] = [:]
        for song in songs {
            let key = song.displayAlbum
            if buckets[key] == nil {
                order.append(key)
                buckets[key] = []
            }
            buckets[key]?.append(song)
        }
        return order
            .map { WatchAlbumGroup(album: $0, songs: sortedByTrackOrder(buckets[$0] ?? [])) }
            .sorted { $0.album.localizedStandardCompare($1.album) == .orderedAscending }
    }

    /// Sorts one album's songs by (discNumber, trackNumber), treating a missing number as sorting
    /// after every numbered song. Relies on `sorted(by:)` being a stable sort (guaranteed since
    /// Swift 5) so songs tied on this key — most commonly two songs both missing a number — keep
    /// their relative arrival order instead of being reshuffled arbitrarily.
    private static func sortedByTrackOrder(_ songs: [WatchTransferMeta]) -> [WatchTransferMeta] {
        songs.sorted { lhs, rhs in
            let lhsDisc = lhs.discNumber ?? Int.max
            let rhsDisc = rhs.discNumber ?? Int.max
            if lhsDisc != rhsDisc { return lhsDisc < rhsDisc }
            let lhsTrack = lhs.trackNumber ?? Int.max
            let rhsTrack = rhs.trackNumber ?? Int.max
            return lhsTrack < rhsTrack
        }
    }

    /// Flattens `songs` into album order: the same per-album buckets `albums(from:)` builds
    /// (keyed by `displayAlbum`, albums sorted alphabetically, each bucket sorted into track order),
    /// with each bucket's songs concatenated back into one list instead of kept as separate album
    /// pages. Mirrors the spirit of the iOS default order (`Song.libraryFlatDisplayOrderAscending`:
    /// album, then disc/track).
    ///
    /// Exists so the Watch's flat "Songs" list can actually form consecutive same-album runs for
    /// `AlbumGrouping.positions(forAlbumKeys:)` — in raw arrival order, runs would rarely form since
    /// a song's neighbours are whatever arrived next from the iPhone, not necessarily its albummates.
    static func songsSortedByAlbum(_ songs: [WatchTransferMeta]) -> [WatchTransferMeta] {
        albums(from: songs).flatMap(\.songs)
    }
}

/// The flat "Songs" list's album-sorted order, bundled together with the per-row
/// `AlbumGroupPosition` each song occupies in that order (see `WatchAlbumGrouping
/// .songsSortedByAlbum` and `AlbumGrouping.positions(forAlbumKeys:)`, the two pure functions this
/// composes). `songs` and `groupPositions` are always the same length and index-aligned, since
/// `WatchSongListView.songList` consumes them together by index.
///
/// Exists so `WatchLocalLibrary` can compute this pair *once* whenever `songs` actually changes
/// (see `WatchLocalLibrary.flatOrder`/`setSongs(_:)`) instead of a SwiftUI view recomputing it
/// inline every time its body evaluates — which, for `WatchSongListView.songList`, turned out to
/// be more often than "the user actually opened the songs list": `NavigationLink(destination:label:)`
/// builds its destination view eagerly as soon as the *label* row appears (confirmed by counting
/// invocations while running the Library page, before ever tapping "曲" — see
/// `progress/watch-ui-redesign.md`), so the sort/group ran on every Library-page render regardless
/// of navigation.
struct WatchFlatSongOrder: Equatable {
    var songs: [WatchTransferMeta]
    var groupPositions: [AlbumGroupPosition]

    static let empty = WatchFlatSongOrder(songs: [], groupPositions: [])

    static func computed(from songs: [WatchTransferMeta]) -> WatchFlatSongOrder {
        let sorted = WatchAlbumGrouping.songsSortedByAlbum(songs)
        let positions = AlbumGrouping.positions(forAlbumKeys: sorted.map(\.displayAlbum))
        return WatchFlatSongOrder(songs: sorted, groupPositions: positions)
    }
}

/// Builds the `MPNowPlayingInfoCenter` payload from Watch playback state, kept as a pure function so
/// the key/value mapping is unit-testable without `MPNowPlayingInfoCenter.default()` (which cannot
/// be observed from an XCTest target).
enum WatchNowPlayingInfoBuilder {
    static func buildInfo(for song: WatchTransferMeta?, isPlaying: Bool, position: Double) -> [String: Any] {
        guard let song else { return [:] }
        return [
            MPMediaItemPropertyTitle: song.displayTitle,
            MPMediaItemPropertyArtist: song.displayArtist,
            MPMediaItemPropertyAlbumTitle: song.displayAlbum,
            MPMediaItemPropertyPlaybackDuration: song.duration,
            MPNowPlayingInfoPropertyElapsedPlaybackTime: position,
            MPNowPlayingInfoPropertyPlaybackRate: isPlaying ? 1.0 : 0.0
        ]
    }
}

#endif
